### ISSUE TITLE
Bugs in JavaScript File.

### ISSUE THREAD

**Issue by AdornChoga** [Kandy-Peter/My-portfolio#11]
Well done on the good job you did on your project. 🥇 

While checking for bugs in your javascript code I found the following bugs. 
I think fixing them can help improve the functionality of your website. 💯 

1. When a user clicks on the see project button the pop-up window does not show. 
I'm positive this bug is coming from [this for loop](https://github.com/Kandy-Peter/My-portfolio/blob/debugging/app.js#L66).
 The condition can be changed from ( i < work.length) to( i <= works.length) to 
ensure the last card object in the works array can be included too in the loop.

2. I also noticed that the form is submitted even if it flags an invalid entry in the email field.
  I suggest that you check the return values of [function for validating ](https://github.com/Kandy-Peter/My-portfolio/blob/debugging/app.js#L130)

**Comment by Kandy-Peter** [comment]
Thank you @AdornChoga!
